apiVersion: apps/v1 
kind: Deployment
metadata:
  name: aws-eks-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-eks-test
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      name: aws-eks-test-pod
      labels:
        app: aws-eks-test
    spec:
      initContainers:
        - name: mysql-wait-init
          image: mysql:8
          command: ['sh', '-c', 'until mysqladmin ping -h"$HOST" -u"$USER" -p"$PASSWORD" --silent; do echo "Waiting for MySQL..."; sleep 5; done']
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER
            - name: PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: HOST
      containers:
        - name: aws-eks-test-container
          image: ramguguloth/test:v1.0
          env:
            - name: NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NAME
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: HOST
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000   