apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard #ebs-sc #standard #ebs-sc 
  resources:
    requests:
      storage: 4Gi 