apiVersion: v1
kind: Service
metadata:
  name: aws-eks-test-nodeport
  namespace: default
  labels:
    app: aws-eks-test
spec:
  type: NodePort
  selector:
    app: aws-eks-test
  ports:
    - protocol: TCP
      port: 8000           # Port to access inside cluster
      targetPort: 8000     # Port your container is exposing
      #nodePort: 30080      # Node port to expose externally
