apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::903724995179:role/sreeram_load_balancer_controller
