apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-eks-test
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: 'monitoring/python-instrumentation'
        #sidecar.opentelemetry.io/inject: 'true'
      name: aws-eks-test-pod
      labels:
        app: aws-eks-test
    spec:
      #serviceAccountName: irsa-demo-sa
      containers:
        - name: aws-eks-test-container
          image: ramguguloth/test:v1.0
          env:
            - name: NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NAME
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: HOST
            - name: PORT
              value: "3306"
            #- name: HOST
            #  value: db-service
            - name: OTEL_PYTHON_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_PYTHON_LOG_FORMAT
              value: "%(asctime)s - %(levelname)s - %(message)s"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_SERVICE_NAME
              value: "aws-eks-python-app"
            - name: DJANGO_SETTINGS_MODULE
              value: job.settings
            - name: PYTHONPATH
              value: /job
          ports:
            - containerPort: 8000  
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  namespace: default  # Change this to your specific namespace
spec:
  selector:
    app: aws-eks-test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
