apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-eks-test
  template:
    metadata:
      name: aws-eks-test-pod
      labels:
        app: aws-eks-test
    spec:
      initContainers:
        - name: mysql-wait-init
          image: mysql:8
          command: ['sh', '-c', 'until mysqladmin ping -h"$HOST" -u"$USER" -p"$PASSWORD" --silent; do echo "Waiting for MySQL..."; sleep 5; done']
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: HOST
      containers:
        - name: aws-eks-test-container
          image: ramguguloth/test2:v1.0
          env:
            - name: NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NAME
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: PASSWORD
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets 
                  key: HOST
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_S3_REGION_NAME
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_S3_REGION_NAME
            - name: AWS_S3_CUSTOM_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_S3_CUSTOM_DOMAIN 
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000   